param(
  [Parameter(Mandatory = $false)]
  [string]$ProjectRef = ""
)

Write-Host "=== Astro Supabase Setup (Terminal-Only) ===" -ForegroundColor Cyan

if ([string]::IsNullOrWhiteSpace($ProjectRef)) {
  Write-Host "ProjectRef not provided. Use your Supabase project ref from dashboard." -ForegroundColor Yellow
  Write-Host "Example: .\scripts\setup\supabase-platform.ps1 -ProjectRef abcdefghijklmnop"
}

Write-Host ""
Write-Host "1) Install Supabase CLI:" -ForegroundColor Yellow
Write-Host "   npm i -g supabase"
Write-Host ""

Write-Host "2) Authenticate:" -ForegroundColor Yellow
Write-Host "   supabase login"
Write-Host ""

if (-not [string]::IsNullOrWhiteSpace($ProjectRef)) {
  Write-Host "3) Link this workspace to project '$ProjectRef':" -ForegroundColor Yellow
  Write-Host "   supabase link --project-ref $ProjectRef"
} else {
  Write-Host "3) Link this workspace to your project:" -ForegroundColor Yellow
  Write-Host "   supabase link --project-ref <PROJECT_REF>"
}

Write-Host ""
Write-Host "4) Push DB migrations:" -ForegroundColor Yellow
Write-Host "   supabase db push"
Write-Host ""

Write-Host "5) Deploy edge functions generated by Astro:" -ForegroundColor Yellow
Write-Host "   supabase functions deploy hello --no-verify-jwt"
Write-Host ""

Write-Host "6) In dashboard verify:" -ForegroundColor Yellow
Write-Host "   - Auth providers"
Write-Host "   - RLS policies"
Write-Host "   - Edge function deployment status"
Write-Host ""

Write-Host "Done. Keep service_role and platform tokens in Supabase/Cloudflare secrets only." -ForegroundColor Green
